// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"errors"
	"testing"

	"url-shortener/internal/storage"
)

// URLSaverMock is a mock implementation of URLSaver interface
type URLSaverMock struct {
	t *testing.T
	// SaveURLFunc allows setting custom behavior for SaveURL method
	SaveURLFunc func(urlToSave, alias string) (int64, error)
}

// NewURLSaverMock creates a new mock instance
func NewURLSaverMock(t *testing.T) *URLSaverMock {
	return &URLSaverMock{
		t: t,
		SaveURLFunc: func(urlToSave, alias string) (int64, error) {
			t.Errorf("SaveURL was called but not mocked")
			return 0, errors.New("not mocked")
		},
	}
}

// SaveURL calls the mocked function
func (m *URLSaverMock) SaveURL(urlToSave, alias string) (int64, error) {
	return m.SaveURLFunc(urlToSave, alias)
}

// Helper methods for common scenarios
func (m *URLSaverMock) SetSaveURLSuccess(id int64) {
	m.SaveURLFunc = func(urlToSave, alias string) (int64, error) {
		return id, nil
	}
}

func (m *URLSaverMock) SetSaveURLError(err error) {
	m.SaveURLFunc = func(urlToSave, alias string) (int64, error) {
		return 0, err
	}
}

func (m *URLSaverMock) SetSaveURLExistsError() {
	m.SaveURLFunc = func(urlToSave, alias string) (int64, error) {
		return 0, storage.ErrURLExists
	}
}
